### PR TITLE
Replace base58-native with bs58 in encrypt/decrypt

### PR DESCRIPTION
**Pull request by gordonwritescode**

### CODE REVIEW

**Comment by braydonf** [comment]
LGTM. 

I've added a test here: https://github.com/gordonwritescode/bitauth/pull/1 to verify that a previously known encrypted message can be decrypted.

**Comment by gordonwritescode** [comment]
@braydonf thanks! @martindale, in the spirit of not merging my own PR, would you mind? :)

**Comment by braydonf** [comment]
Since this is a non-api change we can likely bump to 0.2.1, and npm publish.

**Comment by martindale** [comment]
Looks good.  Merging and shipping.

**Comment by gordonwritescode** [comment]
actually this is probably more accurate:

**Pull request merged**
